version: 0.0
os: linux
files:
  - source: https://s3.amazonaws.com/elasticbeanstalk-us-east-2-780026431059/weather.zip
    destination: /opt/weather_vis_app/
permissions:
  - object: /opt/weather_vis_app/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
# hooks:
#   BeforeInstall:
#     - location: scripts/setup.sh
#       runas: ec2-user
#   AfterInstall:
#     - location: scripts/deploy.sh
#       runas: ec2-user
#       timeout: 300
#   ApplicationStart:
#     - location: app/application.py
#       runas: ec2-user
#       timeout: 60